[ISSofaPython] Fix setting python home with python 2
The fix for python 3 is kept since python changed how it initializes.
I validated with the original committer (@cguyon) that the new behavior
is conceptually correct.

The following errors appeared when using python 2:
> Could not find platform independent libraries <prefix>
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
> ImportError: No module named site

//ref// T8877

(cherry picked from commit 1f646ef48d471c91392a2c0bbba29d71e1bb16f1)